# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agent < Formula
  desc "AgentOS CLI — portable AI agents with a Docker-like UX."
  homepage "https://github.com/asinha07/agentOS"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asinha07/agentOS/releases/download/v0.1.4/agent_0.1.4_darwin_amd64.tar.gz"
      sha256 "dd2b19ee10181aa93e3025893d294994f240aef9ed6b12a705e1fc6f0402b81a"

      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asinha07/agentOS/releases/download/v0.1.4/agent_0.1.4_darwin_arm64.tar.gz"
      sha256 "4b41178c4dfdb2dd8dbaec03bd844ca8b18ead4ca6f35b421f00f98443f0dea0"

      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asinha07/agentOS/releases/download/v0.1.4/agent_0.1.4_linux_amd64.tar.gz"
      sha256 "59111fca8fbd5028ff3c0ecf882bb4c64577e4221b4a3eea983ed79f0b6f6555"
      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asinha07/agentOS/releases/download/v0.1.4/agent_0.1.4_linux_arm64.tar.gz"
      sha256 "a202ded81ad3ccc734490f24cb0e019374134e9ad082b6db121ea6f382a140b8"
      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  test do
    system "#{bin}/agent", "--help"
  end
end
