# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agent < Formula
  desc "AgentOS CLI — portable AI agents with a Docker-like UX."
  homepage "https://github.com/asinha07/agentOS"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asinha07/agentOS/releases/download/v1.0.2/agent_1.0.2_darwin_amd64.tar.gz"
      sha256 "69eb3f00cb91209c74cc1846b435734b180ddc2f818c916bd6bdc47fcd924c21"

      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asinha07/agentOS/releases/download/v1.0.2/agent_1.0.2_darwin_arm64.tar.gz"
      sha256 "a6e683a7f89bfdb190be1b3ad8fa46c41c4958c70cd39c940e39c43bf1bfb99f"

      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asinha07/agentOS/releases/download/v1.0.2/agent_1.0.2_linux_amd64.tar.gz"
      sha256 "d9a7e01de7246fb53b25a0e74a81fe48a5254a913395bfd296f0e594188b065b"
      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asinha07/agentOS/releases/download/v1.0.2/agent_1.0.2_linux_arm64.tar.gz"
      sha256 "c9bdd0c8b84851b084e4e359861bd854e72270c59785a617678b40ae74e20046"
      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  test do
    system "#{bin}/agent", "--help"
  end
end
